# Deployment : Spark Cluster Storage
#VARIABLE:__YOUR_APP__:dtl
#VARIABLE:__YOUR_STORAGE_HOME__:/Users/apple/TEST/spark-kubernetes/LOCAL_STORAGE
---
# History Server Volume Defination
apiVersion: v1
kind: PersistentVolume
metadata:
  name: __YOUR_APP__-spark-history-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "__YOUR_STORAGE_HOME__/spark-history/__YOUR_APP__"

---
# History Server Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __YOUR_APP__-spark-history-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi

---
# History Server Volume Defination
apiVersion: v1
kind: PersistentVolume
metadata:
  name: __YOUR_APP__-spark-app-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "__YOUR_STORAGE_HOME__/spark-app/__YOUR_APP__"

---
# App Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __YOUR_APP__-spark-app-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi


