# Application Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-v-__APP-ID__
  namespace: __APP-NAMESPACE__
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "__PROJECT-ROOT__/__APP-ID__/VOLUMES/apps"

---
# Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-vc-__APP-ID__
  namespace: __APP-NAMESPACE__
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi

---
# Application Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: history-v-__APP-ID__
  namespace: __APP-NAMESPACE__
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "__PROJECT-ROOT__/__APP-ID__/VOLUMES/history/spark"

---
# Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: history-vc-__APP-ID__
  namespace: __APP-NAMESPACE__
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
